# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.11-rc3
yarn_mappings=1.21.11-rc3+build.1
loader_version=0.18.1
loom_version=1.13-SNAPSHOT

# Mod Properties
mod_version=1.0.3+1.21.9
maven_group=com.enbeon.books
archives_base_name=enbeons_custom_books

# Dependencies
fabric_version=0.139.4+1.21.11
yacl_version=3.8.0+1.21.9-fabric
modmenu_version=17.0.0-alpha.1